### ISSUE TITLE
no impl for IncludesPath or IgnoresPath

### ISSUE THREAD

**Issue by termie** [sabhiram/go-gitignore#4]
looks like they are probably going to be implemented based on MatchesPath

**Comment by sabhiram** [comment]
This is what happens when you call play-actions on your code :)

I guess no one was using the interface contracts for those two. But the original intention was that `MatchesPath` would actually be two inversely related functions which made less sense in hind-sight. I will remove the un-neeeded interface defs unless you feel like those are more appropriate?
